spring.config.import=file:env.properties

spring.application.name=demo
spring.data.mongodb.uri=${MONGODB_URI}
spring.data.mongodb.database=${MONGODB_DBNAME}
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}